In [1]:
import numpy as np

In [2]:
# 정수 배열
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [3]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
result = [ num * 3 for num in range(3)]
result

[0, 3, 6]

In [6]:
np.array([ num * 3 for num in range(3)])

array([0, 3, 6])

In [11]:
np.array([range(num, num + 3) for num in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [16]:
np.zeros(0)

array([], dtype=float64)

In [17]:
# 0으로 채원진 길이 10의 정수 배열 만들기
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.ones((3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
# # 1로 채워진 3x5 부동소수 배열 만들기
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.full(10, 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [26]:
np.full((3,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [28]:
np.arange(0, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
# 0과 1 사이에 일정한 간격을 가진 다섯 개의 값으로 채원진 배열 만들기
np.linspace(0, 1, 5) # 0 1 2 3 4 사분위 배열 5개로 쪼개기

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
np.random.random(10) # 0 ~ 1 사이의 값

array([0.08250873, 0.12667343, 0.1659141 , 0.85523231, 0.03162098,
       0.25801203, 0.90038376, 0.11571874, 0.66229208, 0.01542123])

In [35]:
np.random.randint(0, 10, 3) # 정수일때는 구간을 정의 [0, 10]

array([3, 1, 3])

In [36]:
# 구간 [0,10] 사이의 임의의 정수로 채워진 3x3 배열 만들기
np.random.randint(0, 10, (3, 3))

array([[1, 9, 0],
       [9, 4, 4],
       [4, 5, 4]])

In [37]:
np.random.normal(0, 10, (3, 3)) # 표준정규분포(종 모양)

array([[  6.71277878,  10.69131331,   3.1373202 ],
       [-22.07453406,  -4.93278501,   4.95782083],
       [ 15.98029446,  -9.3228993 ,  -1.86025403]])

In [38]:
# 3x3 단위 행렬 만들기
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.empty(3)

array([1., 1., 1.])

In [40]:
np.random.seed(0)
np.random.randint(10)

5

In [41]:
import numpy as np
np.random.seed(0)  # 재현 가능성을 위한 시드 값

x1 = np.random.randint(10, size=6)  # 1차원 배열
x2 = np.random.randint(10, size=(3, 4))  # 2차원 배열
x3 = np.random.randint(10, size=(3, 4, 5))  # 3차원 배열

In [44]:
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [57]:
x1.shape # 배열의크기
x2.shape 
x1.ndim
x2.ndim
x3.ndim
x1.size # 배열 요소의 갯수
x2.size # 12
x1.dtype # 배열의 타입 dtype('int32')

dtype('int32')

In [59]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [60]:
x2.dtype

dtype('int32')

In [62]:
x2[0,0] = 3.14 # 이 값의 소수점 이하는 잘릴 것이다!
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [63]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
x[0:5]
x[:5]  # 첫 다섯 개의 요소

array([0, 1, 2, 3, 4])

In [65]:
x[5:]  # 인덱스 5 다음의 요소들

array([5, 6, 7, 8, 9])

In [66]:
x[4:7]  # 중간 하위 배열

array([4, 5, 6])

In [67]:
x[::2]  # 하나 걸러 하나씩의 요소들로 구성된 배열

array([0, 2, 4, 6, 8])

In [68]:
x[1::2]  # 인덱스 1로부터 시작하여 하나 걸러 하나씩 요소들로 구성된 배열

array([1, 3, 5, 7, 9])

In [69]:
x[::-1]  # 모든 요소들을 거꾸로 나열

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [70]:
x[5::-2]  # 인덱스 5부터 하나 걸러 하나씩 요소들을 거꾸로 나열

array([5, 3, 1])

In [71]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [73]:
x2[2, 3]

7

In [74]:
x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]])

In [75]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [77]:
x2[::-1]

array([[1, 6, 7, 7],
       [7, 6, 8, 8],
       [3, 5, 2, 4]])

In [78]:
x2[:, ::-1]

array([[4, 2, 5, 3],
       [8, 8, 6, 7],
       [7, 7, 6, 1]])

In [76]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [79]:
x2[:, 0]

array([3, 7, 1])

In [81]:
x2[0, :]

array([3, 5, 2, 4])

In [82]:
x2[0] # 0행

array([3, 5, 2, 4])

In [84]:
x2_sub = x2[:2, :2]
x2_sub

array([[3, 5],
       [7, 6]])